 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/address_types", type: :request do
  
  # AddressType. As you add validations to AddressType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AddressType.create! valid_attributes
      get address_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      address_type = AddressType.create! valid_attributes
      get address_type_url(address_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_address_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      address_type = AddressType.create! valid_attributes
      get edit_address_type_url(address_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AddressType" do
        expect {
          post address_types_url, params: { address_type: valid_attributes }
        }.to change(AddressType, :count).by(1)
      end

      it "redirects to the created address_type" do
        post address_types_url, params: { address_type: valid_attributes }
        expect(response).to redirect_to(address_type_url(AddressType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AddressType" do
        expect {
          post address_types_url, params: { address_type: invalid_attributes }
        }.to change(AddressType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post address_types_url, params: { address_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested address_type" do
        address_type = AddressType.create! valid_attributes
        patch address_type_url(address_type), params: { address_type: new_attributes }
        address_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the address_type" do
        address_type = AddressType.create! valid_attributes
        patch address_type_url(address_type), params: { address_type: new_attributes }
        address_type.reload
        expect(response).to redirect_to(address_type_url(address_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        address_type = AddressType.create! valid_attributes
        patch address_type_url(address_type), params: { address_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested address_type" do
      address_type = AddressType.create! valid_attributes
      expect {
        delete address_type_url(address_type)
      }.to change(AddressType, :count).by(-1)
    end

    it "redirects to the address_types list" do
      address_type = AddressType.create! valid_attributes
      delete address_type_url(address_type)
      expect(response).to redirect_to(address_types_url)
    end
  end
end
