 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/boundaries", type: :request do
  
  # OrganizationalBoundary. As you add validations to OrganizationalBoundary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrganizationalBoundary.create! valid_attributes
      get organizational_boundaries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      organizational_boundary = OrganizationalBoundary.create! valid_attributes
      get organizational_boundary_url(organizational_boundary)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_organizational_boundary_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      organizational_boundary = OrganizationalBoundary.create! valid_attributes
      get edit_organizational_boundary_url(organizational_boundary)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrganizationalBoundary" do
        expect {
          post organizational_boundaries_url, params: { organizational_boundary: valid_attributes }
        }.to change(OrganizationalBoundary, :count).by(1)
      end

      it "redirects to the created organizational_boundary" do
        post organizational_boundaries_url, params: { organizational_boundary: valid_attributes }
        expect(response).to redirect_to(organizational_boundary_url(OrganizationalBoundary.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrganizationalBoundary" do
        expect {
          post organizational_boundaries_url, params: { organizational_boundary: invalid_attributes }
        }.to change(OrganizationalBoundary, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post organizational_boundaries_url, params: { organizational_boundary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested organizational_boundary" do
        organizational_boundary = OrganizationalBoundary.create! valid_attributes
        patch organizational_boundary_url(organizational_boundary), params: { organizational_boundary: new_attributes }
        organizational_boundary.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the organizational_boundary" do
        organizational_boundary = OrganizationalBoundary.create! valid_attributes
        patch organizational_boundary_url(organizational_boundary), params: { organizational_boundary: new_attributes }
        organizational_boundary.reload
        expect(response).to redirect_to(organizational_boundary_url(organizational_boundary))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        organizational_boundary = OrganizationalBoundary.create! valid_attributes
        patch organizational_boundary_url(organizational_boundary), params: { organizational_boundary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested organizational_boundary" do
      organizational_boundary = OrganizationalBoundary.create! valid_attributes
      expect {
        delete organizational_boundary_url(organizational_boundary)
      }.to change(OrganizationalBoundary, :count).by(-1)
    end

    it "redirects to the organizational_boundaries list" do
      organizational_boundary = OrganizationalBoundary.create! valid_attributes
      delete organizational_boundary_url(organizational_boundary)
      expect(response).to redirect_to(organizational_boundaries_url)
    end
  end
end
