 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/facility_types", type: :request do
  
  # FacilityType. As you add validations to FacilityType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FacilityType.create! valid_attributes
      get facility_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      facility_type = FacilityType.create! valid_attributes
      get facility_type_url(facility_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_facility_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      facility_type = FacilityType.create! valid_attributes
      get edit_facility_type_url(facility_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FacilityType" do
        expect {
          post facility_types_url, params: { facility_type: valid_attributes }
        }.to change(FacilityType, :count).by(1)
      end

      it "redirects to the created facility_type" do
        post facility_types_url, params: { facility_type: valid_attributes }
        expect(response).to redirect_to(facility_type_url(FacilityType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FacilityType" do
        expect {
          post facility_types_url, params: { facility_type: invalid_attributes }
        }.to change(FacilityType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post facility_types_url, params: { facility_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested facility_type" do
        facility_type = FacilityType.create! valid_attributes
        patch facility_type_url(facility_type), params: { facility_type: new_attributes }
        facility_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the facility_type" do
        facility_type = FacilityType.create! valid_attributes
        patch facility_type_url(facility_type), params: { facility_type: new_attributes }
        facility_type.reload
        expect(response).to redirect_to(facility_type_url(facility_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        facility_type = FacilityType.create! valid_attributes
        patch facility_type_url(facility_type), params: { facility_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested facility_type" do
      facility_type = FacilityType.create! valid_attributes
      expect {
        delete facility_type_url(facility_type)
      }.to change(FacilityType, :count).by(-1)
    end

    it "redirects to the facility_types list" do
      facility_type = FacilityType.create! valid_attributes
      delete facility_type_url(facility_type)
      expect(response).to redirect_to(facility_types_url)
    end
  end
end
