 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ghg_inventories", type: :request do
  
  # GhgInventory. As you add validations to GhgInventory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GhgInventory.create! valid_attributes
      get ghg_inventories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ghg_inventory = GhgInventory.create! valid_attributes
      get ghg_inventory_url(ghg_inventory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ghg_inventory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ghg_inventory = GhgInventory.create! valid_attributes
      get edit_ghg_inventory_url(ghg_inventory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GhgInventory" do
        expect {
          post ghg_inventories_url, params: { ghg_inventory: valid_attributes }
        }.to change(GhgInventory, :count).by(1)
      end

      it "redirects to the created ghg_inventory" do
        post ghg_inventories_url, params: { ghg_inventory: valid_attributes }
        expect(response).to redirect_to(ghg_inventory_url(GhgInventory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GhgInventory" do
        expect {
          post ghg_inventories_url, params: { ghg_inventory: invalid_attributes }
        }.to change(GhgInventory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ghg_inventories_url, params: { ghg_inventory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ghg_inventory" do
        ghg_inventory = GhgInventory.create! valid_attributes
        patch ghg_inventory_url(ghg_inventory), params: { ghg_inventory: new_attributes }
        ghg_inventory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ghg_inventory" do
        ghg_inventory = GhgInventory.create! valid_attributes
        patch ghg_inventory_url(ghg_inventory), params: { ghg_inventory: new_attributes }
        ghg_inventory.reload
        expect(response).to redirect_to(ghg_inventory_url(ghg_inventory))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ghg_inventory = GhgInventory.create! valid_attributes
        patch ghg_inventory_url(ghg_inventory), params: { ghg_inventory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ghg_inventory" do
      ghg_inventory = GhgInventory.create! valid_attributes
      expect {
        delete ghg_inventory_url(ghg_inventory)
      }.to change(GhgInventory, :count).by(-1)
    end

    it "redirects to the ghg_inventories list" do
      ghg_inventory = GhgInventory.create! valid_attributes
      delete ghg_inventory_url(ghg_inventory)
      expect(response).to redirect_to(ghg_inventories_url)
    end
  end
end
